<a href="https://colab.research.google.com/github/nancyngh13-debug/ciencia-de-datos/blob/main/GroupBy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Group by

In [9]:
import pandas as pd

path = '/content/Online_Retail.csv'
retail_data =  pd.read_csv(path, encoding='latin1')
print(type(retail_data))
print(retail_data)

<class 'pandas.core.frame.DataFrame'>
       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER       6.0
1         536365     71053                  WHITE METAL LANTERN       6.0
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER       8.0
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE       6.0
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.       6.0
...          ...       ...                                  ...       ...
155971    550035    15058B         PINK POLKADOT GARDEN PARASOL       2.0
155972    550035     21922    UNION STRIPE WITH FRINGE  HAMMOCK       3.0
155973    550035     22670            FRENCH WC SIGN BLUE METAL       1.0
155974    550035     21672   WHITE SPOT RED CERAMIC DRAWER KNOB       1.0
155975    550035     21080      SET/20 RED RETROSPOT PAPER NAPK       NaN

          InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/10 8:26       2.55     17850.0  United Kingdom
1        12/1/10 8:26       3.39     17850.0  United Kingdom
2        12/1/10 8:26       2.75     17850.0  United Kingdom
3        12/1/10 8:26       3.39     17850.0  United Kingdom
4        12/1/10 8:26       3.39     17850.0  United Kingdom
...               ...        ...         ...             ...
155971  4/14/11 11:48       7.95     15039.0  United Kingdom
155972  4/14/11 11:48       7.95     15039.0  United Kingdom
155973  4/14/11 11:48       1.25     15039.0  United Kingdom
155974  4/14/11 11:48       1.25     15039.0  United Kingdom
155975            NaN        NaN         NaN             NaN

[155976 rows x 8 columns]

In [11]:
contry_count = retail_data['Country'].value_counts()
print(contry_count)

Country
United Kingdom          143768
Germany                   2539
France                    2158
EIRE                      1852
Spain                      779
Netherlands                696
Belgium                    512
Portugal                   490
Australia                  382
Switzerland                371
Cyprus                     306
Finland                    285
Italy                      268
Channel Islands            250
Norway                     212
Japan                      211
Singapore                  118
Sweden                     110
Poland                      98
Hong Kong                   91
Greece                      85
Iceland                     84
Denmark                     59
Austria                     48
Lebanon                     45
Israel                      38
Lithuania                   35
United Arab Emirates        30
Czech Republic              17
Unspecified                 16
Saudi Arabia                10
Canada                      10
Bahrain                      2
Name: count, dtype: int64

In [13]:
country_group = retail_data.groupby('Country')['Quantity'].sum()
print(country_group)

Country
Australia                 25303.0
Austria                    1327.0
Bahrain                       0.0
Belgium                    6028.0
Canada                       88.0
Channel Islands            3471.0
Cyprus                     4252.0
Czech Republic              307.0
Denmark                    1557.0
EIRE                      32546.0
Finland                    5170.0
France                    28934.0
Germany                   29534.0
Greece                     1077.0
Hong Kong                  1853.0
Iceland                    1117.0
Israel                      360.0
Italy                      2629.0
Japan                      8050.0
Lebanon                     386.0
Lithuania                   652.0
Netherlands               59752.0
Norway                     3967.0
Poland                     1310.0
Portugal                   6158.0
Saudi Arabia                 75.0
Singapore                  2475.0
Spain                      8266.0
Sweden                    12323.0
Switzerland                5795.0
United Arab Emirates        496.0
United Kingdom          1162893.0
Unspecified                 282.0
Name: Quantity, dtype: float64

In [ ]:
product_sales = retail_data.groupby('Description')['Quantity'].sum().sort_values(ascending=False)
display(product_sales.head(10))

In [16]:
display(retail_data.describe())

            Quantity      UnitPrice     CustomerID
count  155975.000000  155975.000000  108961.000000
mean        9.093977       5.104240   15291.987610
std       271.106162     100.898659    1732.633843
min    -74215.000000       0.000000   12346.000000
25%         1.000000       1.250000   13842.000000
50%         3.000000       2.460000   15194.000000
75%        10.000000       4.210000   16873.000000
max     74215.000000   16888.020000   18283.000000

In [17]:
country_stats = retail_data.groupby('Country')['UnitPrice'].agg(['mean', 'min', 'max'])
display(country_stats)

                            mean   min       max
Country
Australia               3.981937  0.25    350.00
Austria                 6.637292  0.21     40.00
Bahrain                 3.810000  3.81      3.81
Belgium                 3.553203  0.12     29.95
Canada                  2.063000  0.65      4.95
Channel Islands         4.267560  0.42     50.00
Cyprus                  7.619020  0.21    320.69
Czech Republic          1.872353  0.65      4.95
Denmark                 4.730678  0.42     18.00
EIRE                    7.817997  0.00   1687.17
Finland                 4.841895  0.12    275.60
France                  4.428536  0.16   1136.30
Germany                 3.580772  0.00     35.95
Greece                  4.763529  0.14     50.00
Hong Kong              59.997692  0.21   2583.76
Iceland                 2.679167  0.25     12.75
Israel                  3.909211  0.85     10.95
Italy                   3.992239  0.42     35.00
Japan                   2.383649  0.29     45.57
Lebanon                 5.387556  0.55     14.95
Lithuania               2.841143  1.25      5.95
Netherlands             2.328060  0.21     16.95
Norway                 10.397170  0.29    376.50
Poland                  3.038061  0.42     12.75
Portugal                3.449714  0.21     28.00
Saudi Arabia            2.411000  0.42      5.49
Singapore             106.550424  0.21   2382.92
Spain                   7.620436  0.14   1715.85
Sweden                  3.196455  0.19     40.00
Switzerland             3.717116  0.18     40.00
United Arab Emirates    2.585667  0.65      7.95
United Kingdom          5.007278  0.00  16888.02
Unspecified             2.281250  0.55      7.95

In [18]:
country_stock_group = retail_data.groupby(['Country', 'StockCode'])['Quantity'].sum()
print(country_stock_group)

Country      StockCode
Australia    20665          6.0
             20675        216.0
             20676        216.0
             20677        216.0
             20685         24.0
                          ...
Unspecified  21977         24.0
             22691          2.0
             48116          2.0
             84991         24.0
             84992         24.0
Name: Quantity, Length: 9751, dtype: float64

In [20]:
def total_revenue(group):
  return group['Quantity'] * group['UnitPrice'].sum()
revenue_per_country = retail_data.groupby('Country').apply(total_revenue)
print(revenue_per_country)

Country
Australia    197        9126.6
             198       12168.8
             199       18253.2
             200        9126.6
             201        6084.4
                        ...
Unspecified  152723      438.0
             152724      876.0
             152725      876.0
             152726      876.0
             152727      876.0
Name: Quantity, Length: 155975, dtype: float64

/tmp/ipykernel_3022/2258882689.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  revenue_per_country = retail_data.groupby('Country').apply(total_revenue)